<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TargetPlatformMoniker>Windows,Version=7.0</TargetPlatformMoniker>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MiniPdm.Infrastructure/MiniPdm.Infrastructure.csproj" />
  </ItemGroup>
</Project>
