<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <TargetPlatformMoniker>Windows,Version=7.0</TargetPlatformMoniker>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/MiniPdm.Desktop/MiniPdm.Desktop.csproj" /></ItemGroup>
</Project>
